<Project>
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Authors>KimPig</Authors>
    <Company>KimPig</Company>
    <Product>Subtitle Font Bridge</Product>
    <RepositoryUrl>https://github.com/KimPig/jellyfin-plugin-subtitle-font-bridge</RepositoryUrl>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
