<Project>
  <PropertyGroup>
    <Version>12.0.0.2</Version>
    <AssemblyVersion>12.0.0.2</AssemblyVersion>
    <FileVersion>12.0.0.2</FileVersion>
    <Authors>KimPig</Authors>
    <Company>KimPig</Company>
    <Product>Subtitle Font Bridge</Product>
    <RepositoryUrl>https://github.com/KimPig/jellyfin-plugin-subtitle-font-bridge</RepositoryUrl>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
